export const Fetch_types = {
    MSG_REQUEST : "MSG_REQUEST",
    MSG_SUCCESS : "MSG_SUCCESS",
    MSG_SINGLE_SUCCESS:"MSG_SINGLE_SUCCESS" ,
    MSG_FAILUR : "MSG_FAILUR",
    CLEAR_FETCH : "CLEAR_FETCH"
}